# pytest.ini
[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto

# 테스트 시 경고 출력 제어
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

# 출력 형식 (verbose + short traceback)
addopts = -v --tb=short
