# Generated by Django 5.2.12 on 2026-05-31 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50, verbose_name='메이플스토리 캐릭터명')),
                ('ocid', models.CharField(max_length=100, unique=True, verbose_name='넥슨 Open API 식별자(OCID)')),
                ('world_name', models.CharField(max_length=30, verbose_name='월드 이름')),
                ('is_main', models.BooleanField(default=False, verbose_name='대표 캐릭터 여부')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='본인인증 완료 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '캐릭터 연동',
                'verbose_name_plural': '캐릭터 연동 목록',
            },
        ),
    ]
