# Generated by Django 5.2.12 on 2026-06-04 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 일시'),
        ),
        migrations.AlterField(
            model_name='characterlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='characterlink',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='대표 캐릭터 여부'),
        ),
        migrations.AlterUniqueTogether(
            name='characterlink',
            unique_together={('user', 'character_name')},
        ),
        migrations.AddIndex(
            model_name='characterlink',
            index=models.Index(fields=['user', 'is_main'], name='character_c_user_id_a2f520_idx'),
        ),
        migrations.AddIndex(
            model_name='characterlink',
            index=models.Index(fields=['created_at'], name='character_c_created_b8fe04_idx'),
        ),
    ]
