# Generated by Django 5.2.12 on 2026-06-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_characterlink_updated_at_and_more'),
        ('character', '0002_characterlink_updated_at_constraints_indexes'),
    ]

    operations = [
    ]
