# Generated by Django 5.2.12 on 2026-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='character_ocid',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='maple_nickname',
            field=models.CharField(max_length=12, unique=True, verbose_name='메이플 닉네임'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nexon_api_key',
            field=models.CharField(blank=True, help_text='넥슨 오픈 API 키 (선택사항)', max_length=255, null=True, verbose_name='넥슨 API 키'),
        ),
    ]
