# Generated by Django 5.2.12 on 2026-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='maple_nickname',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, verbose_name='메이플 닉네임'),
        ),
    ]
