# Generated by Django 5.2.12 on 2026-07-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='community_c_categor_c6128e_idx',
            old_name='community_categor_eb9375_idx',
        ),
    ]
