# Generated by Django 5.2.12 on 2026-06-07 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션 목록',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, default='assistant', max_length=20, verbose_name='역할')),
                ('content', models.TextField(blank=True, null=True, verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지 목록',
            },
        ),
        migrations.CreateModel(
            name='MessageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thinking', models.TextField(blank=True, help_text='Qwen Thinking 모델 사고 과정', null=True, verbose_name='LLM 사고 과정')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='응답 시간(ms)')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='사용 모델명')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='토큰 사용량')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 일시')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='chat.chatmessage', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '메시지 메타데이터',
                'verbose_name_plural': '메시지 메타데이터 목록',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='chat_chatse_user_id_47c665_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_chatme_session_70d41b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'role'], name='chat_chatme_session_f09cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemetadata',
            index=models.Index(fields=['message'], name='chat_messag_message_4d4e5c_idx'),
        ),
    ]
