# Generated by Django 5.2.12 on 2026-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemetadata',
            name='route',
            field=models.CharField(blank=True, default='', help_text='chat / knowledge / character / character_knowledge', max_length=30, verbose_name='질문 분류 경로'),
        ),
        migrations.AddField(
            model_name='messagemetadata',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='답변 근거로 사용한 문서 목록 (index, title, url, category, date)', verbose_name='근거 문서'),
        ),
    ]
