# Generated by Django 5.2.12 on 2026-10-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_metadata_route_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='owner_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='비로그인 소유자 세션 키'),
        ),
    ]
