# Generated by Django 5.2.12 on 2026-06-04 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thinking', models.TextField(blank=True, help_text='Qwen Thinking 모델 사고 과정', null=True, verbose_name='LLM 사고 과정')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='응답 시간(ms)')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='사용 모델명')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='토큰 사용량')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '메시지 메타데이터',
                'verbose_name_plural': '메시지 메타데이터 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': '채팅 메시지', 'verbose_name_plural': '채팅 메시지 목록'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': '채팅 세션', 'verbose_name_plural': '채팅 세션 목록'},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='thinking',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='메시지 내용'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, default='assistant', max_length=20, verbose_name='역할'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 일시'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 일시'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 일시'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_chatme_session_70d41b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'role'], name='chat_chatme_session_f09cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='chat_chatse_user_id_47c665_idx'),
        ),
        migrations.AddField(
            model_name='messagemetadata',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='chat.chatmessage', verbose_name='메시지'),
        ),
        migrations.AddIndex(
            model_name='messagemetadata',
            index=models.Index(fields=['message'], name='chat_messag_message_4d4e5c_idx'),
        ),
    ]
