# Generated by Django 5.2.12 on 2026-06-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagemetadata_alter_chatmessage_options_and_more'),
        ('chat', '0006_messagemetadata'),
    ]

    operations = [
    ]
